version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: bookdb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: book-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev
    
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db-data:
